import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service for Addocu',
  description: 'Addocu Terms of Service - The rules and guidelines for using our Google Sheets Add-on.',
};

export default function TermsPage() {
  return (
    <div className="prose prose-lg max-w-none">
      <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms of Service</h1>
      
      <p className="text-gray-600 mb-6">
        <strong>Last Updated:</strong> September 20, 2025
      </p>

      <div className="space-y-8">
        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">1. Acceptance of Terms</h2>
          <p className="text-gray-700 leading-relaxed">
            By installing and using the Addocu Google Sheets™ Add-on (the "Add-on"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not install or use the Add-on.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">2. License</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            The Addocu Add-on is provided as a free, open-source tool under the{' '}
            <a 
              href="https://creativecommons.org/licenses/by-nc-sa/4.0/" 
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#1A5DBB] hover:underline"
            >
              Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License
            </a>.
          </p>
          <p className="text-gray-700 leading-relaxed">
            This license allows you to use, share, and adapt the tool for any non-commercial purpose, provided you give appropriate credit and share any adaptations under the same license. You may not use this tool for commercial purposes.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">3. User Responsibilities</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            You are solely responsible for:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-gray-700">
            <li>Creating and securing your own Google Cloud API Key.</li>
            <li>Ensuring you have the necessary permissions to access the Google platforms you intend to audit.</li>
            <li>Understanding and complying with the terms of service of all Google platforms you use in conjunction with this Add-on.</li>
            <li>Reviewing the data generated by the Add-on and making your own business decisions. The data provided is for informational purposes only.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">4. Disclaimer of Warranties</h2>
          <p className="text-gray-700 leading-relaxed">
            The Add-on is provided **"as is"** and **"as available,"** without warranty of any kind, express or implied. This includes, but is not limited to, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Add-on will be uninterrupted, error-free, secure, or that the data it provides will be accurate or complete. You use the Add-on at your own sole risk.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">5. Limitation of Liability</h2>
          <p className="text-gray-700 leading-relaxed">
            In no event shall the creators of Addocu be liable for any direct, indirect, incidental, special, consequential, or punitive damages, including but not limited to, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of, or inability to access or use, the Add-on. This limitation of liability applies whether the alleged liability is based on contract, tort, negligence, strict liability, or any other basis, even if we have been advised of the possibility of such damage.
          </p>
        </section>
        
        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">6. Governing Law</h2>
          <p className="text-gray-700 leading-relaxed">
            These Terms shall be governed by the laws of Spain, without regard to its conflict of law provisions.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">7. Changes to Terms</h2>
          <p className="text-gray-700 leading-relaxed">
            We reserve the right to modify these Terms at any time. We will notify you of any changes by posting the new Terms on this page. Your continued use of the Add-on after any such changes constitutes your acceptance of the new Terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">8. Contact Us</h2>
          <p className="text-gray-700 leading-relaxed">
            If you have any questions about these Terms of Service, please contact us at{' '}
            <a 
              href="mailto:hola@addocu.com"
              className="text-[#1A5DBB] hover:underline"
            >
              hola@addocu.com
            </a>.
          </p>
        </section>
      </div>
    </div>
  );
}